flowchart TD
    DevSectionView --> DeliveryLists
    DeliveryLists --> FetchCompleted["Fetch Completed"]
    DeliveryLists --> FetchInProgress["Fetch In Progress"]
    FetchCompleted --> DeliveryTable
    FetchInProgress --> DeliveryTable
    DeliveryTable --> DeliveryRow
