flowchart LR
    Activities["fleet-mdm-activities"] --> Join
    HostActivities["fleet-mdm-host-activities"] --> Join
    Join["Left Join (5s window)"] --> AddHeader["Add MessageType Header"]
    AddHeader --> Output["fleet-mdm-events"]
